### ISSUE TITLE
Homework 8 Fixes

### ISSUE THREAD

**Issue by rtrana** [acontreras15/anime-world#2]
This is coming along nicely. You can choose to fix the code or to keep the grade assigned in D2L. Once you complete and push your fixes to GitHub, be sure to close this issue. Closing this issue will notify me - no need to resubmit to D2L.

----

- [x] Remember to close the GitHub issue once you've fixed all the components (close the Homework 7 issue).
- [x] UI Fix: You may want to provide a label on the form for the numeric value otherwise the user doesn't know what they should be entering.

---

Part I: 0.3/0.3

---

Part II: 0.25/0.35
- [x] Clicking on the Cancel button causes a white label error.
- [x] Clicking on the Submit button in edit mode causes a white label error, although it does ultimately update the value in the DB

---

Part III: 0.35/0.35

**Final Score: 0.9/1.0**

**Comment by acontreras15** [comment]
I checked the submit and cancel button in view-anime and they work on my side. Maybe I didn't completely push my changes to github, I did now. Can you check to see if they work now.
